const MAP = {
  ru: {
    week: [
      'Воскресенье',
      'Понедельник',
      'Вторник',
      'Среда',
      'Четверг',
      'Пятница',
      'Суббота',
    ],
    month: [
      'января',
      'февраля',
      'марта',
      'апреля',
      'мая',
      'июня',
      'июля',
      'августа',
      'сентября',
      'октября',
      'ноября',
      'декабря',
    ],
    short: ['Вс', 'Пн', 'Вт', 'Ср', 'Чт', 'Пт', 'Сб'],
    other: [
      'Найти',
      'Найти город',
      'Широта',
      'Долгота',
      'Ощущается как ',
      'Скорость ветра: ',
      ' м/с',
      'Влажность: ',
    ],
    weather: {
      'clear-day': 'безоблачно',
      'clear-night': 'безоблачно',
      'partly-cloudy-day': 'частичная облачность',
      'partly-cloudy-night': 'частичная облачность',
      rain: 'дождь',
      snow: 'снег',
      sleet: 'дождь со снегом',
      wind: 'ветренно',
      fog: 'туман',
      cloudy: 'облачно',
    },
  },
  en: {
    week: [
      'Sunday',
      'Monday',
      'Tuesday',
      'Wednesday',
      'Thursday',
      'Friday',
      'Saturday',
    ],
    month: [
      'January',
      'February',
      'March',
      'April',
      'May',
      'June',
      'July',
      'August',
      'September',
      'October',
      'November',
      'December',
    ],
    short: ['Sun', 'Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat'],
    other: [
      'Search',
      'Search city',
      'Latitude',
      'Longitude',
      'Feels like: ',
      'Wind speed: ',
      ' m/s',
      'Humidity: ',
    ],
    weather: {
      'clear-day': 'cloudless',
      'clear-night': 'cloudless',
      'partly-cloudy-day': 'partially cloudy',
      'partly-cloudy-night': 'partially cloudy',
      rain: 'rain',
      snow: 'snow',
      sleet: 'sleet',
      wind: 'wind',
      fog: 'fog',
      cloudy: 'cloudy',
    },
  },
  be: {
    week: [
      'Нядзеля',
      'Панядзелак',
      'Аўторак',
      'Серада',
      'Чацвер',
      'Пятніца',
      'Субота',
    ],
    month: [
      'студзеня',
      'лютага',
      'сакавіка',
      'красавіка',
      'траўня',
      'чэрвеня',
      'ліпеня',
      'жніўня',
      'верасня',
      'кастрычніка',
      'лістапада',
      'снежня',
    ],
    short: ['Няд', 'Пнд', 'Аўт', 'Сер', 'Чцв', 'Пят', 'Суб', 'Нядзеля'],
    other: [
      'Знайсці',
      'Пошук горада',
      'Шырата',
      'Даўгата',
      'Адчуваецца як: ',
      'Хуткасць ветра: ',
      ' м/с',
      'Вільготнасць: ',
    ],
    weather: {
      'clear-day': 'бясхмарна',
      'clear-night': 'бясхмарна',
      'partly-cloudy-day': 'часткова воблачна',
      'partly-cloudy-night': 'часткова воблачна',
      rain: 'дождж',
      snow: 'снег',
      sleet: 'мокры снег',
      wind: 'вецер',
      fog: 'мгла',
      cloudy: 'воблачна',
    },
  },
  icon: {
    'clear-day': 'clear,sky',
    'clear-night': 'clear,sky',
    'partly-cloudy-day': 'cloud',
    'partly-cloudy-night': 'cloud',
    rain: 'rain',
    snow: 'snowing',
    sleet: 'sleet',
    wind: 'windy',
    fog: 'foggy',
    cloudy: 'cloud',
  },
};

export default MAP;
